### ISSUE TITLE
Add i18n support

### ISSUE THREAD

**Issue by tordans** [basecamp/local_time#22]
Are there any plans to add i18n support @javan?
We would love to use this plugin but our side serves english and german content.
It look like the only similar plugin with i18n support is http://timeago.yarp.com/.

**Comment by azul** [comment]
I think it would be great if the LocalTime.LANG object had the same structure as the i18n date structure. That way it would be fairly easy to import the i18n yaml, export the date part as json and either include it as a constant file or return it with a controller based on the current_users locale.

**Comment by azul** [comment]
Oh... And i think this should be reopened. It was closed because of #21 - which was then closed because of this issue.

**Comment by razy69** [comment]
Hi, thanks for this gem. So when i18n support will be release ?

**Comment by javan** [comment]
[^^^](https://github.com/basecamp/local_time/issues/22#issuecomment-41499931)
> I don't have plans to work on this personally, but I'd be happy to accept a patch.

**Comment by hundsim** [comment]
Have there been any progress on this or still no I18n support? 

Thanks for a super gem!

**Comment by delicious-roasted-turkey** [comment]
I've wrote a quick solution that works for me. It allows to translate month and weekday names only but I guess the same approach could be used for the other strings.

delicious-roasted-turkey/local_time@297cb884a88d058285b4c26fa55cc678c05fb3f1

You can specify the new strings with `setLocalizedStrs`

```javascript
LocalTime.setLocalizedStrs({
  months: ['January', 'February', ... ]
  weekdays: ['Sunday', 'Monday', ... ]
});
```

In my app I am using momentJs so I just do

```javascript
LocalTime.setLocalizedStrs({
  months: moment.localeData(current_locale).months(),
  weekdays: moment.localeData(current_locale).weekdays()
});
```

I'd like to write tests for this but I get an error when I try to run the tests. Has anybody encountered this error?

```
andreu@andreu ~/dev/local_time/local_time $ rake test:javascripts
/home/andreu/.rvm/gems/ruby-2.2.4/gems/childprocess-0.5.9/lib/childprocess/abstract_process.rb:45:in `initialize': all arguments must be String: ["/home/andreu/.rvm/gems/ruby-2.2.4/gems/blade-sauce_labs_plugin-0.4.1/support/sc-linux/bin/sc", "--user", nil, "--api-key", nil, "--tunnel-identifier", "10f39d0a1704df938f09", "--readyfile", "tmp/blade/sauce_tunnel_10f39d0a1704df938f09_ready"] (ArgumentError)
	from /home/andreu/.rvm/gems/ruby-2.2.4/gems/childprocess-0.5.9/lib/childprocess.rb:19:in `new'
	from /home/andreu/.rvm/gems/ruby-2.2.4/gems/childprocess-0.5.9/lib/childprocess.rb:19:in `new'
	from /home/andreu/.rvm/gems/ruby-2.2.4/gems/blade-sauce_labs_plugin-0.4.1/lib/blade/sauce_labs_plugin/tunnel.rb:36:in `create_child_process'
	from /home/andreu/.rvm/gems/ruby-2.2.4/gems/blade-sauce_labs_plugin-0.4.1/lib/blade/sauce_labs_plugin/tunnel.rb:14:in `start'
	from /home/andreu/.rvm/gems/ruby-2.2.4/gems/blade-sauce_labs_plugin-0.4.1/lib/blade/sauce_labs_plugin.rb:16:in `start'
	from /home/andreu/.rvm/gems/ruby-2.2.4/gems/blade-0.4.1/lib/blade.rb:48:in `block (2 levels) in start'
	from /home/andreu/.rvm/gems/ruby-2.2.4/gems/blade-0.4.1/lib/blade.rb:48:in `each'
	from /home/andreu/.rvm/gems/ruby-2.2.4/gems/blade-0.4.1/lib/blade.rb:48:in `block in start'
	from /home/andreu/.rvm/gems/ruby-2.2.4/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `call'
	from /home/andreu/.rvm/gems/ruby-2.2.4/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run_machine'
	from /home/andreu/.rvm/gems/ruby-2.2.4/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run'
	from /home/andreu/.rvm/gems/ruby-2.2.4/gems/blade-0.4.1/lib/blade.rb:47:in `start'
	from /home/andreu/.rvm/gems/ruby-2.2.4/gems/blade-0.4.1/lib/blade/cli.rb:11:in `ci'
	from /home/andreu/.rvm/gems/ruby-2.2.4/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /home/andreu/.rvm/gems/ruby-2.2.4/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/andreu/.rvm/gems/ruby-2.2.4/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /home/andreu/.rvm/gems/ruby-2.2.4/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /home/andreu/.rvm/gems/ruby-2.2.4/gems/blade-0.4.1/exe/blade:9:in `<top (required)>'
	from bin/blade:16:in `load'
	from bin/blade:16:in `<main>'
```
